### PR TITLE
Update MME wheel

### PR DESCRIPTION
**Pull request by dazzariti**
Replace wheel diagram with updated file adding IRUD and reformatting how connect knowledge sources are displayed.

### CODE REVIEW

**Comment by buske** [comment]
Hey @dazzariti, do you want this to replace the image on the main page? If so, you should replace the file at `assets/images/wheel.png` instead of adding a new one, since that's the file that's used both on the main page as well as on `i_am_a_clinician_laboratory.html`.

**Comment by dazzariti** [comment]
Just checking before I do anything drastic, don't see an option to Edit assets/images/wheel.png - should I delete and replace?

image

**Comment by Relequestual** [comment]
I think so. Don't worry too much. The beauty of git (version control) is we can revert if it doesn't work. I've not tried replacing an image directly on the github site before.

**Comment by dazzariti** [comment]
I think I updated the assets/images/wheel.png but created a new pull request while doing so. #63

**Comment by Relequestual** [comment]
Closed in favour of https://github.com/MatchmakerExchange/matchmakerexchange.github.io/pull/63

**Pull request closed without merging**
