### PR TITLE
Updates/issue45 46

### PR DESCRIPTION
**Pull request by jxchong**
This should address issues #44, #45, #46 

@dazzariti had asked to gray out the diagonals of the table (since nodes can't connect to themselves), however the table was already striped with gray, so I went with a "cancel" glyph. Thoughts on how it looks? I can replace with a dark gray or something else but it seemed like this might be more clear.

### CODE REVIEW

**Comment by fschiettecatte** [comment]
Fine with me

**Comment by jxchong** [comment]
screen shot 2017-07-24 at 12 26 40 pm

Here's a screenshot of what it looks like with the cancel glyph

**Comment by buske** [comment]
Fine by me. Thanks for doing this, @jxchong!

**Comment by buske** [comment]
two +1s, so going to merge

**Pull request merged**
